### ISSUE TITLE
Display and handle <input type="file"/>

### ISSUE THREAD

**Issue by shershen08** [mesqueeb/blitzar#134]
Current implementation does not allow to create a custom <input type="file"/> file.

In my field config I set the event property to follow the 'change' event and then trying to fill in the value with file content as so:
```
// other props
 events: {
        change: ($event, context) => {
          if (type === 'file') {
            context.updateField({id: item.id, value: $event.target.files[0]})
          }
        }
      },
```

with this I get - 
```
runtime-dom.esm-bundler.js?d1f7:1237 Uncaught (in promise) 
DOMException: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, 
which may only be programmatically set to the empty string.
```

**Comment by mesqueeb** [comment]
i think there's no way around this limitation as it's the rules of the `input type=file`

the only thing you can do is create your own custom Vue component that's a wrapper of input type=file.

Since blitzar has the philosophy of "bring your own components" providing this for you is out of the scope of this library though 😅 

good luck!
<sub>--<br />Blitzar was made with 💜 by Luca Ban.<br />You cannot sponsor every project, but next time you do, think of <a href="https://github.com/sponsors/mesqueeb">this one</a> for its prolonged maintenance.</sub>
