### ISSUE TITLE
Project Future Plans, Longevity

### ISSUE THREAD

**Issue by eyleron** [mesqueeb/blitzar#70]
I'm intrigued by your work, as I'm looking for a form generator and a schema representation for forms that can be output server-side (e.g. via API) from database-driven app. 

Blitzar appears less verbose than projects like [VFJS](https://github.com/jarvelov/vue-form-json-schema), but I suspect with that comes a tradeoff between terseness and control...like VFJS requires a UI Schema and includes less "magic" than your project, but then that also means one can use whatever layout grid one wants, whereas it appears your project imposes its own grid, for better or for worse?

Long-term, I'm wondering what the plans are, what kind of stability can we look forward to? Is this project being developed/sponsored by a one-man-shop company? Or a company with $millions in revenue that intends to use this as a key piece of its offerings for years to come?

Thanks for any guidance you can offer!

**Comment by mesqueeb** [comment]
thanks for your comment.

> whereas it appears your project imposes its own grid, for better or for worse?

I don't mean to do this at all! I don't want to impose a grid, but I don't have any good ideas how to do it differently right now. Do you have some ideas? I've explained the current situation around styling and the grid in #8  I'd greatly appreciate if you have any input, feel free to post there!

> Is this project being developed/sponsored by a one-man-shop company? Or a company with $millions in revenue that intends to use this as a key piece of its offerings for years to come?

I currently am the only maintainer on this project but if anyone is willing to help out, it's definitely welcome! I do not intend to become a lonely king on a hill with no-one by my side. : D 

I don't have millions in revenue yet, I have 3 Github sponsers so far. I'm open for any support you can offer, here is my sponsors page:
https://github.com/sponsors/mesqueeb

Because only 3 Github sponsors is not enough yet for me to survive, I also code professionally and currently work for 3 companies. I try to use Blitzar in as many projects as I can in these companies, because it makes everything way faster for me. I can output complex forms that require a high volume of changes whenever the client's opinion changes, and with blitzar it's a breeze!! Definitely much faster than messing around with Vue files and manually having the forms inside the template section in my opinion.

There are about 5 projects I personally work on, that are all still active in which Blitzar is used. Whenever I find a bug, I fix it in Blitzar, and it benefits ALL the projects Blitzar is used in. That's the beauty of open source in my opinion! : )

If you start to use Blitzar in a project that makes revenue, I'd highly appreciate any support you can give me via Github sponsors. Because that goes directly to the maintenance and longevity of the project. : )

**Comment by mesqueeb** [comment]
follow this thread for updates on Vue 3:
https://github.com/CyCraft/blitzar/issues/55
